//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsLayer
    {
        public DetailsLayer()
        {
            this.DormitoryInfo = new HashSet<DormitoryInfo>();
        }
    
        public int Id { get; set; }
        public string LayerNumber { get; set; }
        public int DetailsFloorId { get; set; }
    
        public virtual DetailsFloor DetailsFloor { get; set; }
        public virtual ICollection<DormitoryInfo> DormitoryInfo { get; set; }
    }
}
