//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormitoryInfo
    {
        public DormitoryInfo()
        {
            this.StudentRecord = new HashSet<StudentRecord>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationTime { get; set; }
        public int State { get; set; }
        public string Number { get; set; }
        public int Capacity { get; set; }
        public int Already { get; set; }
        public int DetailsLayerId { get; set; }
    
        public virtual ICollection<StudentRecord> StudentRecord { get; set; }
        public virtual DetailsLayer DetailsLayer { get; set; }
    }
}
